[package]
name = "rgw-rest-admin"
description = "The admin ops REST API (rgw_rest_admin.h, rgw_rest_user.cc, rgw_rest_bucket.cc)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rgw-types.workspace = true
rgw-sal.workspace = true
rgw-rest.workspace = true
rgw-auth.workspace = true
rgw-admin-ops.workspace = true
axum.workspace = true
serde_json.workspace = true

[dev-dependencies]
async-trait.workspace = true
chrono.workspace = true
tokio.workspace = true
tower.workspace = true
